#!/bin/sh

. "$BASE_DIRECTORY/config/paths"
. "$BASE_DIRECTORY/config/methods"

NAME="list"
DESCRIPTION="List all available commands."

_invoke() {
  for entry in "$COMMAND_PATH"/*; do
    . "${entry}"

    _yellowLog $NAME
    _greenLog "  $DESCRIPTION"
  done

  _blueLog "visit https://msamgan.github.io/servers/ for documentation"
}
