#!/bin/sh

. "$BASE_DIRECTORY/config/paths"
. "$BASE_DIRECTORY/config/methods"

NAME="project"
DESCRIPTION="Commands for projects.
    list: list all projects in system
    add: to add new project
    remove <project_name>: remove existing project (will remove all services too.)"

_invoke() {

    if [ -z $1 ]; then
        _redLog "Please provide a command"
        _greenLog "$DESCRIPTION"
        exit 0
    fi

    "$1" "$2"
}

list() {
    count=0
    for entry in "$SERVICE_PATH"/*; do
        project_name=$(basename $entry)
        _yellowLog "[$count]: $project_name"
        count=$((count + 1))
    done
}

add() {
    while true; do
        echo -n "Project name (required): "
        read name
        if [ "$name" != "" ]; then
            break
        fi
    done

    if [ -d "$SERVICE_PATH/$name" ]; then
        _redLog "Please choose other project name, name already in use"
        exit 0
    fi

    mkdir -p $SERVICE_PATH/$name
    _greenLog "Project created successfully"
}

remove() {
    if [ -z $1 ]; then
        _redLog "Please provide a project name"
        exit 0
    fi

    rm -rf $SERVICE_PATH/$1
    _redLog "Project along with all services, removed successfully"
}
