#!/bin/sh

. "$BASE_DIRECTORY/config/paths"
. "$BASE_DIRECTORY/config/methods"

NAME="servers"
DESCRIPTION="Running server for the all the services for a specified project."

_invoke() {

  if [ -z $1 ]; then
    _redLog "Please provide a project name"
    exit 0
  fi

  if [ -z "$(ls -A $SERVICE_PATH/$1)" ]; then
    _redLog "No service found, please add service. use: locomo service $1 add"
    exit 0
  fi

  for entry in "$SERVICE_PATH/$1"/*; do
    . "$entry"
    echo Running : "\e[1;32m$NAME\e[0m"
    echo "\e[1;32mExecuting $COMMAND in $DIRECTORY\e[0m"

    gnome-terminal --working-directory="$DIRECTORY" -e "$COMMAND" --title="$1: $NAME"
  done
}
