#!/bin/sh

#Post install script locomotive.

mkdir -p /usr/share/locomo
mv ../commands/ /usr/share/locomo
mv ../config/ /usr/share/locomo
mv ../lmt /usr/bin/lmt

chmod 755 /usr/bin/lmt
chmod 755 -R /usr/share/locomo
