#!/bin/sh

. "$BASE_DIRECTORY/config/paths"
. "$BASE_DIRECTORY/config/methods"

NAME="check"
DESCRIPTION="Check if the the servers are running or not."

_invoke() {
  count=0
  for project in "$SERVICE_PATH"/*; do
    projectName=$(basename $project)
    _yellowLog "[$count]: $projectName"
    if [ ! -z "$(ls -A $project)" ]; then
      for service in "$project"/*; do
        . "$service"
        lsof -i:"$PORT" -P -n | grep "$PORT"
      done
    fi
    count=$((count + 1))
  done
}
